-- Stage 50 migration: run in the Supabase SQL editor after schema_stage49.
--
-- Phase 3 of the roadmap — School Billing. Confirmed design decisions:
-- one school per Reseeti business account (matches the existing
-- one-business-per-account model exactly, no new "which school" concept
-- needed anywhere); a parent can have multiple children, each gets a
-- fully separate invoice (no combined-invoice logic to build); fee
-- invoices are generated by a manual "Generate invoices for this term"
-- action for now, not true automatic recurring billing (that depends on
-- the recurring-invoice engine, a separate, not-yet-built Phase 2 item).
--
-- Parents are NOT a new table — they're just customers (reusing the
-- existing `customers` table, Stage 6). This is deliberate: it means
-- the existing Customers page, debtor list, and payment history all
-- automatically work correctly for parents with zero new code, purely
-- because a student's generated invoice links to a real customer row
-- the same way any other invoice does.
--
-- Every RLS policy below uses my_active_business_ids() (the safe
-- SECURITY DEFINER helper from schema_stage8_fix.sql/35) from the
-- start, not a raw self-referencing subquery — avoiding the exact class
-- of recursion bug that took most of a day to fully track down and fix
-- across older tables earlier in this project.

create table if not exists school_classes (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references businesses(id) on delete cascade not null,
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (business_id, name)
);

create table if not exists school_sessions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references businesses(id) on delete cascade not null,
  name text not null, -- e.g. "2025/2026"
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists school_terms (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references businesses(id) on delete cascade not null,
  session_id uuid references school_sessions(id) on delete cascade not null,
  name text not null, -- "First Term"
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists students (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references businesses(id) on delete cascade not null,
  name text not null,
  class_id uuid references school_classes(id) on delete set null,
  -- References the existing customers table — a student's "parent" is
  -- just a normal customer, so their generated fee invoices show up in
  -- the existing Customers/debtor UI automatically. Nullable: a student
  -- can be added before their parent's contact is on file yet, though
  -- invoice generation skips anyone without one linked (see the
  -- generate-invoices route).
  parent_customer_id uuid references customers(id) on delete set null,
  admission_number text,
  status text not null default 'active' check (status in ('active', 'inactive', 'graduated')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_students_business on students(business_id);
create index if not exists idx_students_parent on students(parent_customer_id);

create table if not exists fee_structures (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references businesses(id) on delete cascade not null,
  class_id uuid references school_classes(id) on delete cascade not null,
  term_id uuid references school_terms(id) on delete cascade not null,
  -- One row per fee component (Tuition, Feeding, Transport, ...) rather
  -- than one lump sum per class/term — a generated invoice ends up with
  -- real itemized line items, not a single opaque "School Fees" amount.
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- Links a generated fee invoice back to the student/term it was for —
-- both nullable and unrelated to any other invoice field, so every
-- existing invoice (with neither set) and every non-school business
-- using Reseeti are completely unaffected by these columns existing.
alter table invoices add column if not exists student_id uuid references students(id) on delete set null;
alter table invoices add column if not exists term_id uuid references school_terms(id) on delete set null;

alter table school_classes enable row level security;
alter table school_sessions enable row level security;
alter table school_terms enable row level security;
alter table students enable row level security;
alter table fee_structures enable row level security;

create policy "Members manage school classes" on school_classes for all
  using (business_id in (select my_active_business_ids()))
  with check (business_id in (select my_active_business_ids()));

create policy "Members manage school sessions" on school_sessions for all
  using (business_id in (select my_active_business_ids()))
  with check (business_id in (select my_active_business_ids()));

create policy "Members manage school terms" on school_terms for all
  using (business_id in (select my_active_business_ids()))
  with check (business_id in (select my_active_business_ids()));

create policy "Members manage students" on students for all
  using (business_id in (select my_active_business_ids()))
  with check (business_id in (select my_active_business_ids()));

create policy "Members manage fee structures" on fee_structures for all
  using (business_id in (select my_active_business_ids()))
  with check (business_id in (select my_active_business_ids()));
