'use client';

// A receipt for what a business paid Reseeti for its own Pro
// subscription — distinct from the customer-facing invoices the rest of
// this app generates. Simple enough (a handful of text lines, no
// layout worth screenshotting) that this uses jsPDF's own drawing API
// directly rather than the html2canvas-based renderElementToPDFBlob
// pattern the customer invoice receipt uses — no hidden DOM element
// needed for something this plain.
export async function downloadSubscriptionReceipt({ business, event }) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  const gatewayLabel = event.gateway || 'Paystack';
  const amount = event.amount != null ? `NGN ${Number(event.amount).toLocaleString('en-NG')}` : 'N/A';
  const date = new Date(event.created_at).toLocaleDateString('en-NG', { day: '2-digit', month: 'long', year: 'numeric' });

  let y = 60;
  const line = (text, size = 11, bold = false, gap = 20) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(size);
    doc.text(text, 50, y);
    y += gap;
  };

  line('Reseeti', 20, true, 30);
  line('Subscription payment receipt', 12, false, 36);

  line(`Billed to: ${business.name}`, 11, true);
  if (business.address) line(business.address, 10, false, 16);
  if (business.phone) line(business.phone, 10, false, 24);
  else y += 8;

  line('Description: Reseeti Pro subscription', 11);
  line(`Payment method: ${gatewayLabel}`, 11);
  if (event.reference) line(`Reference: ${event.reference}`, 11);
  line(`Date: ${date}`, 11, false, 30);

  doc.setDrawColor(200);
  doc.line(50, y, 545, y);
  y += 24;

  line(`Amount paid: ${amount}`, 14, true, 30);

  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text('Generated by Reseeti — reseeti.app', 50, 780);

  doc.save(`Reseeti-subscription-receipt-${event.reference || event.id}.pdf`);
}
